# example netlify.toml
[build]
  command = "yarn run build"
  # functions = "functions"
  publish = "public"

[dev] # https://github.com/netlify/netlify-dev-plugin#project-detection
  command = "yarn start" # Command to start your dev server
  port = 3000 # Port that the dev server will be listening on
  publish = "dist" # Folder with the static content for _redirect file

[[redirects]]
  from = "/en/*"
  to = "/en/:splat"
[[redirects]]
  from = "/pt/*"
  to = "/pt/:splat"

[[redirects]]
  from = "/*"
  to = "/pt/:splat"
  status = 302
  conditions = {Language = ["pt"]}
[[redirects]]
  from = "/*"
  to = "/en/:splat"
  status = 302
  # conditions = {Language = ["en"]} ## disable for fallback

## more info https://www.netlify.com/docs/netlify-toml-reference/